name: commands workflow

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          deprecated=true  
          if [[ deprecated ]]; then
           echo "::warning::Deprecated function found"
           fi
      # assume we check and see deprecated func
