name: commands workflow 3

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a file exists
        run: |
          if [ -f "config.yml" ]; then
           echo "::debug::config.yml exists"
          else
           echo "::error::config.yml missing"
          fi
