name: jobs workflow 2

on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm install
          npm run build
        working-directory: ./temp
        shell: bash  
        # pwsh, cmd, powershell, python
        
      - run: print("Hello!")
        shell: python
    
